spring:
  datasource:
    url: jdbc:mysql://localhost:3307/yam?useSSL=false&serverTimezone=UTC&useCursors=false&sendStringParametersAsUnicode=false&characterEncoding=UTF8
    username: root
    password: pass
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: localhost
    password:
    port: 6379
