create table account
(
    id                             bigint generated by default as identity,
    email                          varchar(255) not null,
    email_check_token              varchar(255),
    email_check_token_generated_at timestamp,
    email_verified                 boolean      not null,
    joined_at                      timestamp,
    last_modified_at               timestamp,
    role                           varchar(255) not null,
    password                       varchar(255) not null,
    withdraw                       boolean      not null,
    withdrawal_at                  timestamp,
    member_id                      bigint,
    primary key (id)
);

create table member(
    id                             bigint generated by default as identity,
    nickname                       varchar(255) not null,
    image                          varchar(255) not null,
    primary key (id)
);

alter table account
    add constraint UK_q0uja26qgu1atulenwup9rxyr unique (email);

alter table account
    add constraint FKr5j0huynd7nsv1s7e9vb8qvwo foreign key (member_id) references member;
